### ISSUE TITLE
artikel seite erstellen

### ISSUE THREAD

**Issue by mrbubbles-src** [mrbubbles-src/manuelFahrenholzSPAFinalProject#9]
artikel auf hover/click auf der selben seite öffnen (modal?) (desktop)

mobile: artikel cards ähnlich wie dektop auf click ? | "mehr anzeigen" clicken und rest text wird angezeigt + "weniger anzeigen" zum verstecken

artikel die drauf kommen:
- impfungen
- zahnmedizin
- kastration
- reptilien

**Comment by mrbubbles-src** [comment]
artikel auf hover/click auf der selben seite öffnen (modal?) (desktop)

mobile: artikel cards ähnlich wie dektop auf click ? | "mehr anzeigen" clicken und rest text wird angezeigt + "weniger anzeigen" zum verstecken

**Comment by Katharina-Groller** [comment]
+ cards seperat erstellen für mehrfach benutzung ( artikel & Landingpage)
